Update sonar-buildspec.yml

diff --git a/sonar-buildspec.yml b/sonar-buildspec.yml
--- a/sonar-buildspec.yml
+++ b/sonar-buildspec.yml
@@ -57,4 +57,17 @@ phases:
         \"report\": . }" sonarqube_scanreport.json > payload.json
       - |
       - cat payload.json
+        if [ $quality_status = "ERROR" ] || [ $quality_status = "WARN" ]; then
+          aws lambda invoke --function-name ImportVulToSecurityHub --payload file://payload.json sonarqube_scan_report.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          echo "in quality_status ERROR or WARN condition"
+          exit 1;
+        elif [ $quality_status = "OK" ]; then
+          echo "in quality_status OK condition"
+        else
+          echo "in quality_status  unexpected condition"
+          exit 1;
+        fi
+artifacts:
+  type: zip
+  files: '**/*'
       
